export interface WebsitePlan {
  id: "starter" | "pro";
  name: string;
  price: string;
  hosting: string;
  summary: string;
  featured?: boolean;
}

export interface ComparisonFeature {
  feature: string;
  starter: boolean;
  pro: boolean;
}

export const websitePlans: WebsitePlan[] = [
  {
    id: "starter",
    name: "Starter",
    price: "$750",
    hosting: "$49.99/mo",
    summary: "Everything a small business needs to launch with confidence.",
  },
  {
    id: "pro",
    name: "Pro",
    price: "$1,500",
    hosting: "$99.99/mo",
    summary: "Advanced systems for businesses ready to sell, automate, and scale.",
    featured: true,
  },
];

export const buildFeatures: ComparisonFeature[] = [
  {
    feature: "Up to 10 different pages",
    starter: true,
    pro: true,
  },
  {
    feature: "Use of photos provided by you or professionally generated by us",
    starter: true,
    pro: true,
  },
  {
    feature: "Mobile, tablet, and desktop support",
    starter: true,
    pro: true,
  },
  {
    feature: "Custom demo within 2 business days of your request",
    starter: true,
    pro: true,
  },
  {
    feature: "You don’t pay until the website is exactly what you want",
    starter: true,
    pro: true,
  },
  {
    feature: "Third-party integrations",
    starter: false,
    pro: true,
  },
  {
    feature: "Payment processing",
    starter: false,
    pro: true,
  },
  {
    feature: "Signed-in customer workflows",
    starter: false,
    pro: true,
  },
  {
    feature: "3D animations",
    starter: false,
    pro: true,
  },
];

export const hostingFeatures: ComparisonFeature[] = [
  {
    feature: "We will host your website for you",
    starter: true,
    pro: true,
  },
  {
    feature: "We will do unlimited updates to your website",
    starter: true,
    pro: true,
  },
  {
    feature: "Updates completed in under 2 business days",
    starter: true,
    pro: true,
  },
];
