CREATE TABLE IF NOT EXISTS leads (
    place_id text PRIMARY KEY,
    cid text,
    name text NOT NULL,
    category text,
    all_categories jsonb NOT NULL DEFAULT '[]'::jsonb,
    phone text,
    full_address text,
    street text,
    city text,
    state text,
    zip_code text,
    country text NOT NULL DEFAULT 'United States',
    latitude double precision,
    longitude double precision,
    plus_code text,
    website_raw text,
    website_type text,
    website_explanation text,
    has_website boolean NOT NULL,
    rating double precision,
    reviews_count integer NOT NULL DEFAULT 0 CHECK (reviews_count >= 0),
    is_claimed text,
    price_level text,
    business_status text,
    maps_url text,
    search_keyword text,
    search_location text,
    scraped_at timestamptz NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_leads_no_website_scraped_at
    ON leads (scraped_at DESC) WHERE NOT has_website;
CREATE INDEX IF NOT EXISTS idx_leads_website_type ON leads (website_type);
CREATE INDEX IF NOT EXISTS idx_leads_state ON leads (state);
CREATE INDEX IF NOT EXISTS idx_leads_city ON leads (city);
CREATE INDEX IF NOT EXISTS idx_leads_category ON leads (category);
CREATE INDEX IF NOT EXISTS idx_leads_phone ON leads (phone);
CREATE INDEX IF NOT EXISTS idx_leads_is_claimed ON leads (is_claimed);

CREATE TABLE IF NOT EXISTS search_queue (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword text NOT NULL,
    location_name text NOT NULL,
    latitude double precision,
    longitude double precision,
    zoom_level integer NOT NULL DEFAULT 14,
    bounding_box text,
    status text NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'in_progress', 'completed', 'failed')),
    results_found integer NOT NULL DEFAULT 0 CHECK (results_found >= 0),
    leads_saved integer NOT NULL DEFAULT 0 CHECK (leads_saved >= 0),
    error_message text,
    attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at timestamptz,
    UNIQUE (keyword, location_name)
);

CREATE INDEX IF NOT EXISTS idx_queue_status_id ON search_queue (status, id);
CREATE INDEX IF NOT EXISTS idx_queue_keyword ON search_queue (keyword);

CREATE TABLE IF NOT EXISTS lead_emails (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id text NOT NULL REFERENCES leads(place_id) ON DELETE CASCADE,
    email text NOT NULL,
    source_url text,
    source_type text,
    confidence double precision NOT NULL DEFAULT 0.70 CHECK (confidence BETWEEN 0 AND 1),
    is_free_provider boolean NOT NULL DEFAULT true,
    discovered_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (place_id, email)
);

CREATE INDEX IF NOT EXISTS idx_lead_emails_place_id ON lead_emails (place_id);
CREATE INDEX IF NOT EXISTS idx_lead_emails_email ON lead_emails (email);

CREATE TABLE IF NOT EXISTS quarantined_emails (
    email text PRIMARY KEY,
    reason text NOT NULL,
    occurrences integer NOT NULL DEFAULT 1 CHECK (occurrences > 0),
    first_quarantined_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS email_extraction_status (
    place_id text PRIMARY KEY REFERENCES leads(place_id) ON DELETE CASCADE,
    status text NOT NULL CHECK (status IN ('completed', 'no_email', 'error')),
    emails_found_count integer NOT NULL DEFAULT 0 CHECK (emails_found_count >= 0),
    processed_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_email_status ON email_extraction_status (status);

CREATE TABLE IF NOT EXISTS campaigns (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    status text NOT NULL DEFAULT 'running'
        CHECK (status IN ('running', 'completed', 'stopped', 'failed')),
    target_jobs integer NOT NULL DEFAULT 0 CHECK (target_jobs >= 0),
    search_workers integer NOT NULL CHECK (search_workers > 0),
    email_workers integer NOT NULL CHECK (email_workers > 0),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at timestamptz
);

ALTER TABLE search_queue
    ADD COLUMN IF NOT EXISTS campaign_id bigint REFERENCES campaigns(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_queue_campaign_status_id
    ON search_queue (campaign_id, status, id);
CREATE INDEX IF NOT EXISTS idx_search_queue_campaign_claimable
    ON search_queue (campaign_id, id)
    WHERE status = 'pending' OR (status = 'failed' AND attempts < 3);

CREATE TABLE IF NOT EXISTS email_queue (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    campaign_id bigint NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
    place_id text NOT NULL REFERENCES leads(place_id) ON DELETE CASCADE,
    status text NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'in_progress', 'completed', 'no_email', 'failed')),
    attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    emails_found integer NOT NULL DEFAULT 0 CHECK (emails_found >= 0),
    error_message text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at timestamptz,
    completed_at timestamptz,
    UNIQUE (campaign_id, place_id)
);

CREATE INDEX IF NOT EXISTS idx_email_queue_campaign_claimable
    ON email_queue (campaign_id, id)
    WHERE status = 'pending' OR (status = 'failed' AND attempts < 3);
CREATE INDEX IF NOT EXISTS idx_email_queue_campaign_status
    ON email_queue (campaign_id, status);
CREATE INDEX IF NOT EXISTS idx_email_queue_place_id ON email_queue (place_id);
