import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { ArrowLeft, ExternalLink, ImageIcon, Send, Wrench } from "lucide-react";
import { markWebsiteLive, publishDemo, setProductionStatus, updateTicket } from "@/app/admin/actions";
import { SiteHeader } from "@/components/site-header";
import { formatDate, formatRequestNumber, statusLabels, type RequestAsset, type WebsiteRequest } from "@/lib/customer-lifecycle";
import { WEBSITE_REQUEST_PHOTO_BUCKET } from "@/lib/website-request";
import { createClient } from "@/lib/supabase/server";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Manage website request" };
type PageProps = { params: Promise<{ id: string }> };
const fieldClass = "mt-2 w-full border border-white/14 bg-black/30 px-4 py-3 text-sm text-white outline-none focus:border-[#c9ff3b]";

export default async function AdminRequestPage({ params }: PageProps) {
  const requestId = Number((await params).id);
  if (!Number.isInteger(requestId) || requestId < 1) notFound();
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/start?mode=signin");
  const { data: admin } = await supabase.rpc("is_keeplyn_admin");
  if (!admin) redirect("/portal");
  const { data, error } = await supabase.from("website_requests").select("*, website_request_offerings(*), website_request_assets(*), website_request_updates(*)").eq("id", requestId).single();
  if (error || !data) notFound();
  const request = data as WebsiteRequest;
  request.website_request_offerings?.sort((a, b) => a.position - b.position);
  request.website_request_updates?.sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());
  const assets = request.website_request_assets ?? [];
  if (assets.length) {
    const { data: signed } = await supabase.storage.from(WEBSITE_REQUEST_PHOTO_BUCKET).createSignedUrls(assets.map((asset) => asset.storage_path), 3600);
    request.website_request_assets = assets.map((asset, index) => ({ ...asset, signedUrl: signed?.[index]?.signedUrl }));
  }

  return <main className="min-h-svh bg-[#050505] text-white"><SiteHeader /><section className="site-container py-12 sm:py-18"><Link href="/admin" className="inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.12em] text-white/38 hover:text-white"><ArrowLeft className="size-3.5" />Build queue</Link><div className="mt-8 flex flex-col gap-7 border-b border-white/10 pb-10 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-[#c9ff3b]">Request {formatRequestNumber(request.id)}</p><h1 className="mt-5 text-[clamp(3.5rem,8vw,6.5rem)] font-semibold leading-[0.8] tracking-[-0.08em]">{request.customer_name || "Customer website"}</h1><p className="mt-5 text-sm text-white/42">{request.customer_email} · {statusLabels[request.status]}</p></div>{request.demo_url ? <a href={request.demo_url} target="_blank" rel="noreferrer" className="button-primary">Open demo <ExternalLink className="size-4" /></a> : null}</div><div className="mt-8 grid gap-8 xl:grid-cols-[minmax(0,1fr)_24rem]"><div className="space-y-8">
    <section className="border border-white/12 bg-white/[0.02] p-6 sm:p-8"><h2 className="text-3xl font-semibold tracking-[-0.05em]">Production controls</h2><div className="mt-6 flex flex-wrap gap-3">{(["in_review", "in_progress", "launching"] as const).map((status) => <form action={setProductionStatus} key={status}><input type="hidden" name="requestId" value={request.id} /><input type="hidden" name="status" value={status} /><button className="button-secondary !px-4 !py-2.5" disabled={request.status === status}>{status.replace("_", " ")}</button></form>)}</div><form action={publishDemo} className="mt-8 border-t border-white/10 pt-6"><input type="hidden" name="requestId" value={request.id} /><label className="block text-xs font-semibold text-white/62">Secure demo URL<input type="url" name="demoUrl" required pattern="https://.*" defaultValue={request.demo_url ?? ""} className={fieldClass} placeholder="https://demo.example.com" /></label><button className="button-primary mt-4"><Send className="size-4" />Publish demo & email customer</button></form>{request.paid_at ? <form action={markWebsiteLive} className="mt-8 border-t border-white/10 pt-6"><input type="hidden" name="requestId" value={request.id} /><label className="block text-xs font-semibold text-white/62">Live website URL<input type="url" name="liveUrl" required pattern="https://.*" defaultValue={request.live_url ?? (request.domain_name ? `https://${request.domain_name}` : "")} className={fieldClass} /></label><button className="button-primary mt-4"><ExternalLink className="size-4" />Mark live & email customer</button></form> : null}</section>
    <section className="border border-white/12 bg-white/[0.02] p-6 sm:p-8"><h2 className="text-3xl font-semibold tracking-[-0.05em]">Customer brief</h2><dl className="mt-7 grid gap-6 sm:grid-cols-2"><Info label="Plan" value={request.plan_id} /><Info label="Submitted" value={formatDate(request.created_at)} /><Info label="Photo direction" value={request.photo_brief || "Not specified"} /><Info label="Theme" value={request.theme_description || "Not specified"} /><div className="sm:col-span-2"><Info label="Additional notes" value={request.additional_notes || "None"} /></div></dl><h3 className="mt-8 border-t border-white/10 pt-6 text-sm font-semibold">Offerings</h3><div className="mt-3 divide-y divide-white/10">{request.website_request_offerings?.map((offering) => <div key={offering.id} className="py-4"><div className="flex justify-between gap-3"><p className="font-semibold">{offering.title}</p><p className="text-[#c9ff3b]">${Number(offering.price).toFixed(2)}</p></div><p className="mt-2 text-sm leading-6 text-white/44">{offering.description}</p></div>)}</div></section>
    <section className="border border-white/12 bg-white/[0.02] p-6 sm:p-8"><h2 className="text-3xl font-semibold tracking-[-0.05em]">Customer photos</h2>{request.website_request_assets?.length ? <div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3">{request.website_request_assets.map((asset: RequestAsset) => asset.signedUrl ? <a key={asset.id} href={asset.signedUrl} target="_blank" rel="noreferrer"><Image unoptimized src={asset.signedUrl} alt={asset.original_filename} width={600} height={600} className="aspect-square w-full object-cover opacity-80 hover:opacity-100" /><span className="mt-2 block truncate text-[10px] text-white/32">{asset.original_filename}</span></a> : null)}</div> : <p className="mt-4 flex items-center gap-2 text-sm text-white/38"><ImageIcon className="size-4" />No uploaded photos.</p>}</section>
    <section className="border border-white/12 bg-white/[0.02] p-6 sm:p-8"><h2 className="text-3xl font-semibold tracking-[-0.05em]">Update tickets</h2>{request.website_request_updates?.length ? <div className="mt-6 space-y-4">{request.website_request_updates.map((ticket) => <article key={ticket.id} className="border border-white/10 p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{ticket.title}</h3><p className="mt-2 text-xs text-white/28">{formatDate(ticket.created_at)}</p></div><span className="text-[10px] uppercase tracking-[0.12em] text-[#c9ff3b]">{ticket.status.replace("_", " ")}</span></div><p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-white/48">{ticket.description}</p>{ticket.status !== "completed" ? <form action={updateTicket} className="mt-5 border-t border-white/10 pt-5"><input type="hidden" name="ticketId" value={ticket.id} /><label className="block text-xs font-semibold text-white/58">Response to customer<textarea name="response" maxLength={5000} defaultValue={ticket.admin_response ?? ""} className={`${fieldClass} min-h-28 resize-y`} /></label><div className="mt-4 flex flex-wrap gap-3"><button name="status" value="in_progress" className="button-secondary !px-4 !py-2.5"><Wrench className="size-4" />Mark in progress</button><button name="status" value="completed" className="button-primary !px-4 !py-2.5">Complete & email customer</button></div></form> : ticket.admin_response ? <p className="mt-4 border-l-2 border-[#c9ff3b] pl-4 text-sm text-white/62">{ticket.admin_response}</p> : null}</article>)}</div> : <p className="mt-4 text-sm text-white/38">No update tickets.</p>}</section>
  </div><aside className="h-fit border border-white/12 bg-white/[0.025] p-6 xl:sticky xl:top-24"><p className="text-[10px] uppercase tracking-[0.14em] text-white/28">Launch details</p><dl className="mt-6 space-y-5"><Info label="Status" value={statusLabels[request.status]} /><Info label="Approved" value={formatDate(request.approved_at)} /><Info label="Domain" value={request.domain_name || "Not entered"} /><Info label="Hosting" value={request.hosting_selected ? request.hosting_status : "Not selected"} /><Info label="Payment" value={request.payment_status.replace("_", " ")} /><Info label="Paid" value={formatDate(request.paid_at)} /></dl></aside></div></section></main>;
}

function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-[10px] uppercase tracking-[0.14em] text-white/26">{label}</dt><dd className="mt-2 whitespace-pre-wrap text-sm capitalize leading-6 text-white/62">{value}</dd></div>; }
